spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  profiles:
    include: local, oauth
