--insert into members(nick_name, email, created_date, last_modified_date)
--values ('남지민', 'namjimin@idle.com', now(), now());
--insert into members(nick_name, email, created_date, last_modified_date)
--values ('이주영', 'leejuyoung@idle.com', now(), now());
--insert into members(nick_name, email, created_date, last_modified_date)
--values ('김하은', 'kimhaen@idle.com', now(), now());
--insert into members(nick_name, email, created_date, last_modified_date)
--values ('성정혜', 'sungjunghae@idle.com', now(), now());
--insert into members(nick_name, email, created_date, last_modified_date)
--values ('김연경', 'kimyunkyung@idle.com', now(), now());
--
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 1, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 1, now(), now());
--
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 2, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 2, now(), now());
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 3, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 3, now(), now());
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 4, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 4, now(), now());
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 5, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 5, now(), now());
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 6, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 6, now(), now());
--
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('연봉', 1, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('산업군', 2, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('위치(거리)', 3, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('워라밸', 4, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('네임밸류', 5, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', 6, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('사내문화', 7, 7, now(), now());
--insert into member_criteria (criteria_name, weight, member_id, created_date, last_modified_date)
--values ('복지', 8, 7, now(), now());
--
--
--
--insert notice(title, url, member_id, created_date, last_modified_date)
--values ('K뱅크 규제시스템 담당자 채용', 'https://kbank.recruiter.co.kr/app/jobnotice/view?systemKindCode=MRS2&jobnoticeSn=109399',
--        1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('연봉', '4200', 2, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('산업군', '금융 IT', 1, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('위치(거리)', '상암동', 2, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('워라밸', '대체로 만족', 3, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('네임밸류', '', 1, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', '불투명', 1, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('사내문화', '최악꼰대', 1, 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('복지', '하나도없음', 1, 1, now(), now());
--
--
--insert notice(title, url, member_id, created_date, last_modified_date)
--values ('[신한은행] App서비스 기획/운영 경력직 채용', 'https://shinhan.recruiter.co.kr/appsite/company/index', 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('연봉', '6500', 3, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('산업군', '은행', 2, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('위치(거리)', '시청역', 2, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('워라밸', '부바부헬', 2, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('네임밸류', '4대은행', 3, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', '불투명', 1, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('사내문화', '진심꼰대', 1, 2, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('복지', '은근 많음', 2, 2, now(), now());
--
--insert notice(title, url, member_id, created_date, last_modified_date)
--values ('(주)아이엠비씨 직원 채용 공고', 'https://www.imbc.com/notice/notice_2018/3671051_75022.html', 1, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('연봉', '4500', 1, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('산업군', '방송국', 2, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('위치(거리)', '상암동', 2, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('워라밸', '천국', 3, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('네임밸류', '', 2, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', '', 1, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('사내문화', '모름, 은근 젊을듯', 2, 3, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('복지', '없다', 1, 3, now(), now());
--
--
--
--insert notice(title, url, member_id, created_date, last_modified_date)
--values ('오토에버 데이터플랫폼/기준정보 부문 경력 채용',
--        'https://hyundai-autoever.recruiter.co.kr/app/jobnotice/view?systemKindCode=MRS2&jobnoticeSn=86226', 1, now(),
--        now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('연봉', '7000', 3, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('산업군', 'SI업체', 1, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('위치(거리)', '양재동', 1, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('워라밸', '헬', 1, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('네임밸류', '대표 SI', 2, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('(회사)성장 가능성', '없음', 1, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('사내문화', '나름 젊음', 2, 4, now(), now());
--insert notice_criteria(criteria_name, description, score, notice_id, created_date, last_modified_date)
--values ('복지', '차량 할인', 3, 4, now(), now());
--
--
--
--
--
